### ISSUE TITLE
sonos | Not using?

### ISSUE THREAD

**Issue by Symbiot78** [Aleborg/homeassistant-aleborg-frontend#5]
Hi

So continuing my journey through your dashboard - I wanted to get my sonos added under one of the rooms.

if I understand correctly the room tab would use the include.yaml from here:

aleborg_frontend\templates\partials\media\auto-entities

and looking in the yaml file it appears that you are excluding speaker device class - which of course sonos is. but maybe that's on purpose.
I then tried adding my own:

`#############################################
- entity_id: media_player.*
  area: {{title}}
  integration: "Sonos"
  attributes:
    device_class: speaker
  options: !include ../sonos/media_sonos.yaml`

but it makes no difference.. it ignores my device and gives me a blank page.

I've triple checked that my sonos device in in the "kitchen" area - which now is setup correctly.

so should the auto-entities not be picking this up?

![image](https://user-images.githubusercontent.com/3314249/234403749-a2cd162a-17a6-4616-b2e6-d5901020e228.png)

**Comment by Aleborg** [comment]
Just noticed that there is a problem in that file, my setup is a little different, I have a Sonos mediaplayer that is connected to an input in a receiver, depending on what input you select, the selected source is displayed.

Try to add this in `aleborg_frontend\templates\partials\media\auto-entities\include.yaml`:

```yaml
- entity_id: media_player.*
  area: {{title}}
  device_manufacturer: Sonos
  options: !include ../sonos/media_sonos.yaml
```

**Comment by Symbiot78** [comment]
At first try that did not help. Didn’t have time to play around with it though.
But adding it did nothing.

**Comment by Aleborg** [comment]
When you do changes to any yaml file, do a small change in tablet.yaml as well, just a new line (empty), ha won't notice changes to other files.

**Comment by Symbiot78** [comment]
Tried your trick
Also remove device manufacturer
No luck

**Comment by Symbiot78** [comment]
I tried adding it to the lights section.
here it works. it fails because it cannot find the sonos card (which i didn't add to the path) - so fair enough that it throws an error. But it actually tries.

so area etc is correct. But no matter what I try I cannot get the media card to pickup the sonos.
Even if i hardcode the entity_id as I did with the lights..

this in the include.yaml for media:

- entity_id: media_player.kitchen_sonos
  # area: "kitchen" #"{{title}}"
  # device_manufacturer: Sonos
#  options: !include ../sonos/media_sonos.yaml

Does NOT work.

but adding it to include.yaml in lights.. and it is added to the lights section.

**Comment by Symbiot78** [comment]
hm.... I've tried every iteration and combination of files & parameters I can think of. I simply cannot get the sonos entity to show under media tab.

**Comment by Aleborg** [comment]
Ok, so this is my `templates\partials\media\auto-entities\include.yaml` file right now. 
With this code I get the Sonos card

```yaml
# lovelace_gen

# Receivers and speakers
#############################################
- entity_id: media_player.*
  area: {{title}}
  not:
    integration: "cast"
  or:
    - attributes:
        device_class: speaker
    - attributes:
        device_class: receiver
  options: !include ../receiver/media_receiver.yaml

  # Chromecast speakers
  #############################################
- entity_id: media_player.*
  area: {{title}}
  integration: "cast"
  not:
    - attributes:
        device_class: tv
  options: !include ../cast/media_cast_speaker.yaml
  
  # Chromecast TV's
  #############################################
- entity_id: media_player.*
  area: {{title}}
  integration: "cast"
  attributes:
    device_class: tv
  options: !include ../cast/media_cast_tv.yaml


- entity_id: media_player.*
  area: {{title}}
  attributes:
    media_content_id: "*sonos*"
  options: !include ../sonos/media_sonos.yaml
```
